'use client';
import React, { useEffect, useState } from 'react';
import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";
import { useRouter } from 'next/navigation';

import jsonData from '../data/album.json';
import 'bootstrap/dist/css/bootstrap.min.css';
import { DndProvider } from 'react-dnd';
import { HTML5Backend } from 'react-dnd-html5-backend';

// import 'bootstrap/dist/js/bootstrap.min.js';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  const { push } = useRouter();
  const [image, setImage] = useState(null);
  const [backgroundImage, setBackgroundImage] = useState(null);
  const [backgroundImageUrl, setBackgroundImageUrl] = useState(null);
  const [backgroundImageType, setBackgroundImageType] = useState(null);
  const images = []
  jsonData.map(d=>{
    images.push({type:d.type, ...d.images[0]})
  });
  const [backgrounds, setBackgrounds] = useState(images);

  const useTemplate = (selectedBackground)=>{
    console.log({selectedBackground: selectedBackground.type});
    push({
        pathname: '/editor',
        query: { type: selectedBackground.type}
    });
  }

  return (
    <>

    

      <Head>
        <title>Texture Image Editor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>      
      <header>
        <div class="collapse bg-dark" id="navbarHeader">
          <div class="container">
            <div class="row">
              <div class="col-sm-8 col-md-7 py-4">
                <h4 class="text-white">About</h4>
                <p class="text-muted-custom">
                Frentils Technology is the online invitation card makers bring convenience to the forefront. With just a few clicks, you can create and send beautiful invitations from the comfort of your home. Simply choose a template, customize it to your liking, and share it with your guests through email or social media.
                </p>
              </div>
              <div class="col-sm-4 offset-md-1 py-4">
                <h4 class="text-white">Contact</h4>
                <ul class="list-unstyled">
                  <li><a href="#" class="text-white">Email me</a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div class="navbar navbar-dark bg-dark shadow-sm">
          <div class="container d-flex justify-content-between">
            <a href="#" class="navbar-brand d-flex align-items-center">
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="mr-2" viewBox="0 0 24 24" focusable="false"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path><circle cx="12" cy="13" r="4"></circle></svg>
              <strong> Frentils Image Editor</strong>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          </div>
        </div>
      </header>
      <main role="main">

  <section class="jumbotron text-center">
    <div class="container">
      <h1 class="jumbotron-heading"><b>Choose Background</b></h1>
      <p class="lead text-muted">select a background and edit text for your invitations</p>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">

      <div class="row">
      {
      backgrounds.map((bg) => (
        <div class="col-md-3">
          <div class="card mb-4 shadow-sm img-center">
            <img src={bg.url} class="bd-placeholder-img card-img-top"/>
            {/* <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg> */}
            <div class="card-body">
              <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-secondary" onClick={()=>useTemplate(bg)}>Use this template</button>
                </div>
              </div>
            </div>
          </div>
        </div>
      ))
    }
      </div>
    </div>
  </div>

</main>
    </>
  );
}
